In [2]:
import numpy as np
import pandas as pd
works = pd.DataFrame({
'작가': ['김유정', '김유정', '김유정',
'현진건', '현진건',
'이상', '이상',
'나도향', '나도향',
'채만식', '이효석'],
'작품': ['봄봄', '동백꽃', '만무방',
'운수 좋은 날', 'B사감과 러브레터',
'날개', '권태',
'벙어리 삼룡이', '물레방아',
'레디메이드 인생', '메밀꽃 필 무렵'],
'연도': [1935, 1936, 1934,
1924, 1925,
1936, 1937,
1925, 1925,
1934, np.nan], # 이효석 '메밀꽃 필 무렵' 발표연도가 누락됨
'글자수': [12500, 9800, 13600,
11200, 7400,
18300, 14100,
16800, 14500,
22000, 11800],
})
authors = pd.DataFrame({
'작가': ['김유정', '현진건', '이상', '나도향', '채만식', '이효석', '염상섭'],
'생년': [1908, 1900, 1910, 1902, 1902, 1907, 1897],
'몰년': [1937, 1943, 1937, 1926, 1950, 1942, 1963],
})

In [3]:
print(works)
print(authors)

     작가         작품      연도    글자수
0   김유정         봄봄  1935.0  12500
1   김유정        동백꽃  1936.0   9800
2   김유정        만무방  1934.0  13600
3   현진건    운수 좋은 날  1924.0  11200
4   현진건  B사감과 러브레터  1925.0   7400
5    이상         날개  1936.0  18300
6    이상         권태  1937.0  14100
7   나도향    벙어리 삼룡이  1925.0  16800
8   나도향       물레방아  1925.0  14500
9   채만식   레디메이드 인생  1934.0  22000
10  이효석   메밀꽃 필 무렵     NaN  11800
    작가    생년    몰년
0  김유정  1908  1937
1  현진건  1900  1943
2   이상  1910  1937
3  나도향  1902  1926
4  채만식  1902  1950
5  이효석  1907  1942
6  염상섭  1897  1963

In [ ]:
#Q1-a
print(works.shape)
print(works.dtypes)
works.describe()
#works, dtypes,describe의 속성을 프린트해야한다

(11, 4)
작가         str
작품         str
연도     float64
글자수      int64
dtype: object

                연도           글자수
count    10.000000     11.000000
mean   1931.100000  13818.181818
std       5.546771   4080.641661
min    1924.000000   7400.000000
25%    1925.000000  11500.000000
50%    1934.000000  13600.000000
75%    1935.750000  15650.000000
max    1937.000000  22000.000000

In [ ]:
#짧은 관찰:NaN은 결측치를 나타내는 값으로, 일반적인 정수형 int에는 포함될 수 없다. 그래서 정수처럼 보이는 열에 NaN이 섞이면 pandas는 보통 그 열을 float64로 바꾸어 저장한다. 한편 숫자와 문자열 등 여러 자료형이 섞여 있으면 pandas는 더 포괄적인 자료형인 object로 처리한다.

In [ ]:
#Q1-b
print(works.isna().sum())
#isna().sum은 각 열에 대해 결측치의 개수를 알려준다

작가     0
작품     0
연도     1
글자수    0
dtype: int64

In [7]:
#작가, 작품, 글자수 열에는 결측치가 없지만 연도 열에 결측치가 1개 있다

In [ ]:
#Q1-c
works2 = works.fillna(1936)
works2["연도"] = works2["연도"].astype(int)

print(works2.dtypes)
print(works2.tail(3))
#fillna()로 결측치를 채울 수 있고 astype()으로 형변환을 할 수 있다

작가       str
작품       str
연도     int64
글자수    int64
dtype: object
     작가        작품    연도    글자수
8   나도향      물레방아  1925  14500
9   채만식  레디메이드 인생  1934  22000
10  이효석  메밀꽃 필 무렵  1936  11800

In [ ]:
#Q2-1
after_1930=works2[works2["연도"]>=1930]["작품"]
print(after_1930)
kim_or_lee = works2.loc[works2["작가"].isin(["김유정", "이상"]), "작품"]
print(kim_or_lee)

#불인덱싱을 하여 연도가 1930년대 이후에 태어난 것들만 골라서 새로운 표를 만들 수 있고 loc을 이용해서 열 이름으로 접근할 수 있다

0           봄봄
1          동백꽃
2          만무방
5           날개
6           권태
9     레디메이드 인생
10    메밀꽃 필 무렵
Name: 작품, dtype: str
0     봄봄
1    동백꽃
2    만무방
5     날개
6     권태
Name: 작품, dtype: str

In [ ]:
#Q2-b
def categorize(n:int)->str:
    if n <10000:
        return "짧음"
    elif n >= 10000 and n <= 15000:
        return "보통"
    elif n>15000:
        return "긴"
works2["분량"]=works2["글자수"].apply(categorize)
works2[["작품","글자수","분량"]]

#미리 categorize라는 함수를 정의해두고 그것을 apply를 이용해서 적용해서 새로운 열을 추가할 수 있다

           작품    글자수  분량
0          봄봄  12500  보통
1         동백꽃   9800  짧음
2         만무방  13600  보통
3     운수 좋은 날  11200  보통
4   B사감과 러브레터   7400  짧음
5          날개  18300   긴
6          권태  14100  보통
7     벙어리 삼룡이  16800   긴
8        물레방아  14500  보통
9    레디메이드 인생  22000   긴
10   메밀꽃 필 무렵  11800  보통

In [ ]:
print(works2.sort_values(["연도","글자수"],ascending=[True,False]))
#sort_values는 오름차순 혹은 내림차순으로 지정한 열을 정렬할 수 있다. 먼저 나온 열을 기준으로 정렬을 하고 같은 값일 경우 두번째 지정한 열을 기준으로 정렬한다

     작가         작품    연도    글자수  분량
3   현진건    운수 좋은 날  1924  11200  보통
7   나도향    벙어리 삼룡이  1925  16800   긴
8   나도향       물레방아  1925  14500  보통
4   현진건  B사감과 러브레터  1925   7400  짧음
9   채만식   레디메이드 인생  1934  22000   긴
2   김유정        만무방  1934  13600  보통
0   김유정         봄봄  1935  12500  보통
5    이상         날개  1936  18300   긴
10  이효석   메밀꽃 필 무렵  1936  11800  보통
1   김유정        동백꽃  1936   9800  짧음
6    이상         권태  1937  14100  보통

In [ ]:
#Q3-a
print(works2.groupby('작가')['글자수'].agg(["mean","count","sum"]))
#열의 값이 작가인 것들끼리 묶어서 글자수들의 평균, 총합, 횟수 등을 groupby와 agg로 고를 수 있다

             mean  count    sum
작가
김유정  11966.666667      3  35900
나도향  15650.000000      2  31300
이상   16200.000000      2  32400
이효석  11800.000000      1  11800
채만식  22000.000000      1  22000
현진건   9300.000000      2  18600

In [ ]:
#Q3-b
print(works2["분량"].value_counts())
#value_counts는 열 이름이 분량에 해당하는 것에서 각 값들이 몇번 등장하는지 알려준다. 여기서 분량이라는 열에서 보통은 총 6번, 긴은 3번, 짧음은 2번 나온다

분량
보통    6
긴     3
짧음    2
Name: count, dtype: int64

In [ ]:
#Q3-c
print(works2.groupby(["작가","분량"]).size())
#관찰: 가장 많은 양을 차지한 것은 김유정의 보통분량 소설이다. 이를 통해 김유정은 평소에 단편소설보다 중편 길이의 소설을 썼음을 확인할 수 있따
#그룹바이의 그룹키를 리스트로 주면 작가별로 한 번 묶고, 분량별로 한 번 묶는다

작가   분량
김유정  보통    2
     짧음    1
나도향  긴     1
     보통    1
이상   긴     1
     보통    1
이효석  보통    1
채만식  긴     1
현진건  보통    1
     짧음    1
dtype: int64

In [ ]:
#Q4-a
full=pd.merge(works2,authors,on="작가",how='left')
print(full)
print(full.shape)
#works2와 authors 데이터를 합치는데 작가라는 콜롬으로 합치고 왼쪽 데이터, 즉 works2를 기준으로 합친다
#확인질문:how= left즉 왼쪽에 있는 데이터인 works2를 기준으로 합쳐서 works2에 있는 것들만 포함하고 authors에만 있는 작가들은 포함하지 않는다

     작가         작품    연도    글자수  분량    생년    몰년
0   김유정         봄봄  1935  12500  보통  1908  1937
1   김유정        동백꽃  1936   9800  짧음  1908  1937
2   김유정        만무방  1934  13600  보통  1908  1937
3   현진건    운수 좋은 날  1924  11200  보통  1900  1943
4   현진건  B사감과 러브레터  1925   7400  짧음  1900  1943
5    이상         날개  1936  18300   긴  1910  1937
6    이상         권태  1937  14100  보통  1910  1937
7   나도향    벙어리 삼룡이  1925  16800   긴  1902  1926
8   나도향       물레방아  1925  14500  보통  1902  1926
9   채만식   레디메이드 인생  1934  22000   긴  1902  1950
10  이효석   메밀꽃 필 무렵  1936  11800  보통  1907  1942
(11, 7)

In [ ]:
# Q4-b
full["집필 당시 나이"] = full["연도"] - full["생년"]
print(full)
#새열을 추가하기 위해 full의 연도 콜롬을 가져오고 생년 콜롬을 가져와서 집필당시나이를 만든다

     작가         작품    연도    글자수  분량    생년    몰년  집필 당시 나이
0   김유정         봄봄  1935  12500  보통  1908  1937        27
1   김유정        동백꽃  1936   9800  짧음  1908  1937        28
2   김유정        만무방  1934  13600  보통  1908  1937        26
3   현진건    운수 좋은 날  1924  11200  보통  1900  1943        24
4   현진건  B사감과 러브레터  1925   7400  짧음  1900  1943        25
5    이상         날개  1936  18300   긴  1910  1937        26
6    이상         권태  1937  14100  보통  1910  1937        27
7   나도향    벙어리 삼룡이  1925  16800   긴  1902  1926        23
8   나도향       물레방아  1925  14500  보통  1902  1926        23
9   채만식   레디메이드 인생  1934  22000   긴  1902  1950        32
10  이효석   메밀꽃 필 무렵  1936  11800  보통  1907  1942        29

In [ ]:
#Q4-c
print(full.groupby("작가")['집필 당시 나이'].mean().sort_values(ascending=True))
#작가 콜롬에서 값이 같은 것 끼리 합치고 집필당시나이의 평균을 가져오고 그것을 오름차순으로 정리한다
#해석: 앞서 만든 full과 현재 출력된것으로 보았을 때 가장 어릴때 작품을 집필한 작가는 나도향을 23에 집필을 했고 평균 23살에 집필을 했다. 반면가장 늦은 나이에 집필을 한 것은 채만식이다

작가
나도향    23.0
현진건    24.5
이상     26.5
김유정    27.0
이효석    29.0
채만식    32.0
Name: 집필 당시 나이, dtype: float64

In [ ]:
#https://chatgpt.com/c/6a1a7172-7300-83a8-ae95-b896fda45551